### ISSUE TITLE
Domain / package

### ISSUE THREAD

**Issue by ryantheleach** [YggLabs/GordianKnot#1]
Does ygglabs have a standard package / domain name? Otherwise I'm happy to keep this under au.id.rleach but would prefer it under something ygglabs related. Also since it probably wasn't explicitly stated earlier, copyright on my contribution is assigned to YggLabs to publish under any license they choose.

**Comment by Inscrutable** [comment]
I haven't done anything about the domain name for this. How does that stuff usually work? 
We should probably agree on some form of License for Code and Text. I suggest MIT and CC-BY respectively, unless we need to restrict access.

**Comment by vectrixdevelops** [comment]
For LabyRegen I've used `io/github/ygglabs/` as it is a domain we already own from GitHub (https://ygglabs.github.io) by having this organization. I've also added the MIT license on LabyRegen too. These can be changed to your liking though. 😄
